### PR TITLE
JMLdoc Doclet Extension Based Design, Making it Build Independent

### PR DESCRIPTION
**Pull request by arjunmitrareddy**
@leavens @davidcok 
Please check the PR. Currently testing with commit before B144. 
This new design potentially makes it build independent from now on.
Will push b144+ code if everything is fine with the PR.
Do not merge this.

### CODE REVIEW

**Comment by arjunmitrareddy** [comment]
@leavens @davidcok 
Just check these files, ignore remaining:
1) All the builders in OpenJML\src\org\jmlspecs\openjml\jmldoc\builders
2) Modified Writers in OpenJML\src\org\jmlspecs\openjml\jmldoc\writers
3) doclet.xml resource file in OpenJML\src\org\jmlspecs\openjml\jmldoc\resources
4) Test files in OpenJML\src\org\jmlspecs\openjml\jmldoc\test

Thank You.

Regards,
Arjun Mitra Reddy Donthala

**Comment by jsinglet** [comment]
@arjunmitrareddy 

1) This PR has merge conflicts. Please create a clean PR with no conflicts. 
2) Can you please include some unit tests with this feature?

**Comment by jsinglet** [comment]
Also, several places use System.out.println in this merge. Take a look at the various I/O methods used (for example Log.instance(context).noticeWriter.println) and see if you can't find a more appropriate method.

**Comment by arjunmitrareddy** [comment]
@jsinglet 
Thank you for the comments. Will be pushing the PR with no conflicts soon. It has conflicts because I was working on an older commit. 
Sure will take a look at the I/O methods.

**Comment by arjunmitrareddy** [comment]
Closing this. Made new one for b144+

**Pull request closed without merging**
